import { EditorThemeClasses } from 'lexical'

export const theme: EditorThemeClasses = {
  code: 'not-prose codeBlock',
  codeHighlight: {
    atrule: 'tokenAttr',
    attr: 'tokenAttr',
    boolean: 'tokenProperty',
    builtin: 'tokenSelector',
    cdata: 'tokenComment',
    char: 'tokenSelector',
    class: 'tokenFunction',
    'class-name': 'tokenFunction',
    comment: 'tokenComment',
    constant: 'tokenProperty',
    deleted: 'tokenProperty',
    doctype: 'tokenComment',
    entity: 'tokenOperator',
    function: 'tokenFunction',
    important: 'tokenVariable',
    inserted: 'tokenSelector',
    keyword: 'tokenAttr',
    namespace: 'tokenVariable',
    number: 'tokenProperty',
    operator: 'tokenOperator',
    prolog: 'tokenComment',
    property: 'tokenProperty',
    punctuation: 'tokenPunctuation',
    regex: 'tokenVariable',
    selector: 'tokenSelector',
    string: 'tokenSelector',
    symbol: 'tokenProperty',
    tag: 'tokenProperty',
    url: 'tokenOperator',
    variable: 'tokenVariable',
  },
  text: {
    bold: 'bold',
    code: 'code',
    italic: 'italic',
    strikethrough: 'strikethrough',
    subscript: 'subscript',
    superscript: 'superscript',
    underline: 'underline',
    underlineStrikethrough: 'underlineStrikethrough',
  },

  list: {
    nested: {
      listitem: 'nestedListItem',
    },
  },

  admonition: {
    danger: 'danger',
    info: 'info',
    note: 'note',
    tip: 'tip',
    caution: 'caution',
  },
}
